# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('date', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=250)),
                ('size', models.CharField(max_length=32)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Post')),
            ],
        ),
    ]
