# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='link',
            new_name='itemLink',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='itemName',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='itemReview',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='size',
            new_name='itemSize',
        ),
    ]
